"""add external_id to events, extend sources, add scrape_runs

Revision ID: 7e15486bd51c
Revises: 051b966c7e58
Create Date: 2026-09-26 00:45:35.763958

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '7e15486bd51c'
down_revision: Union[str, None] = '051b966c7e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_date', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('raw_html', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parsed_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('success', 'partial', 'failure', name='scraperunstatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('finished_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_runs_source_name'), ['source_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_runs_target_date'), ['target_date'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_source'), ['source'], unique=False)

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('homepage', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('category_hint', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('trust', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('records_last_run', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_column('records_last_run')
        batch_op.drop_column('last_error')
        batch_op.drop_column('schedule')
        batch_op.drop_column('trust')
        batch_op.drop_column('category_hint')
        batch_op.drop_column('homepage')
        batch_op.drop_column('enabled')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_source'))
        batch_op.drop_index(batch_op.f('ix_events_external_id'))
        batch_op.drop_column('external_id')

    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_runs_target_date'))
        batch_op.drop_index(batch_op.f('ix_scrape_runs_source_name'))

    op.drop_table('scrape_runs')
    # ### end Alembic commands ###
